### ISSUE TITLE
win整合包上传音色后报错 No module named modules.speaker

### ISSUE THREAD

**Issue by ShannonZ** [CCmahua/ChatTTS-Enhanced#15]
[forge_20240724_082828_563849.zip](https://github.com/user-attachments/files/16359459/forge_20240724_082828_563849.zip)
zip文件中是提交的音色文件
报错信息如下：
![image](https://github.com/user-attachments/assets/daa53fb3-eb31-4c5f-99d9-3efb57e3f316)

下载自夸克网盘
操作系统win11

**Comment by CCmahua** [comment]
解压尝试用bandizip试下

**Comment by ShannonZ** [comment]
还是一样
