### ISSUE TITLE
ubuntu 22.04 conda 安装deepspeed 出错 

### ISSUE THREAD

**Issue by OxygenLost** [CCmahua/ChatTTS-Enhanced#3]
Collecting deepspeed==0.12.4 (from resemble-enhance)
  Using cached deepspeed-0.12.4.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h8_p2s8f/deepspeed_914d9f3c80434ef18a62bcb9b7387387/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-h8_p2s8f/deepspeed_914d9f3c80434ef18a62bcb9b7387387/op_builder/builder.py", line 50, in installed_cuda_version
          raise MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
      op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by CCmahua** [comment]
```
MissingCUDAException("CUDA_HOME does not exist, unable to compile CUDA op(s)")
op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)
```

检查本机cuda环境

**Comment by OxygenLost** [comment]
是需要手动安装 cuda 吗？

Døm ***@***.***>于2024年6月24日 周一17:33写道：

**Comment by klmmlk** [comment]
天啦撸，搞个只要CPU的版本啊。我大intel一无是处啊。
