### ISSUE TITLE
请问api怎么使用

### ISSUE THREAD

**Issue by tjglfglf** [CCmahua/ChatTTS-Enhanced#6]
我看见api.py提供了api，我怎样通过外部发送http请求来访问呢，http://0.0.0.0:5000/generate_audio访问提示未授权

**Comment by tjglfglf** [comment]
我使用的是mac的安装包，安装包是不是没对外提供api

**Comment by CCmahua** [comment]
安装包里没更新api，api需自行部署使用

**Comment by tjglfglf** [comment]
谢谢，已经部署完了，非常好用
